services:
  database:
    image: postgres:15.4
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_PORT=${DATABASE_PORT}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - database-data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      # dockerfile: Dockerfile
    env_file:
      - .env
    # environment:
    #   - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:${DATABASE_PORT}/${POSTGRES_DB}
    ports:
      - '3000:3000'
    depends_on:
      - database

volumes:
  database-data:
