"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Comment = exports.Station = exports.Landmark = exports.User = void 0;
const user_1 = __importDefault(require("./user"));
exports.User = user_1.default;
const landmark_1 = __importDefault(require("./landmark"));
exports.Landmark = landmark_1.default;
const station_1 = __importDefault(require("./station"));
exports.Station = station_1.default;
const comment_1 = __importDefault(require("./comment"));
exports.Comment = comment_1.default;
landmark_1.default.belongsTo(station_1.default, { foreignKey: 'stationId' });
station_1.default.hasMany(landmark_1.default, { foreignKey: 'stationId' });
comment_1.default.belongsTo(user_1.default, { foreignKey: 'userId' });
user_1.default.hasMany(comment_1.default, { foreignKey: 'userId' });
comment_1.default.belongsTo(landmark_1.default, { foreignKey: 'landmarkId' });
landmark_1.default.hasMany(comment_1.default, { foreignKey: 'landmarkId' });
